routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/tweets', 'TweetController@index')->name('home');
    Route::post('/tweets', 'TweetController@store');
    Route::post('/profiles/{user:username}/follow', 'FollowsController@store');
    Route::get('/profiles/{user:username}/edit', 'ProfilesController@edit');
    Route::patch('/profiles/{user:username}', 'ProfilesController@update');
    Route::post('/tweets/{tweet}/like', 'TweetLikesController@store');
    Route::delete('/tweets/{tweet}/like', 'TweetLikesController@destroy');

    Route::get('/profiles/{user:username}/edit-banner', 'ProfilesController@editBanner');
    Route::patch('/profiles/{user:username}/update-banner', 'ProfilesController@updateBanner');
    Route::get('/profiles/{user:username}/edit-description', 'ProfilesController@editDescription');
    Route::patch('/profiles/{user:username}/update-description', 'ProfilesController@updateDescription');
});

Route::delete('/tweets/{tweet}/delete', 'TweetController@destroy');

Route::get('/profiles/{user:username}', 'ProfilesController@show')->name('profile');

Route::get('/explore', 'ExploreController@index')->name('explore');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, Followable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute($value)
    {
        return asset($value ?: '/images/default.png');
    }

    public function getBannerAttribute($value)
    {

        return asset($value ?: '/images/default.png');
    }
    // mutator for password misal $user->password = 'ccccc' harus di bycript
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function timeline()
    {
        // ambil data tweet yang user id nya sama dengan user yang login
        // ambil dari orang yang di follow

        $friends = $this->follows()->pluck('id'); // semua id teman2

        return Tweet::whereIn('user_id', $friends)
            ->orWhere('user_id', $this->id)
            ->withLikes()
            ->latest()
            ->get();
    }

    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    public function tweets()
    {
        return $this->hasMany(Tweet::class)->latest();
    }

    public function path($append = '')
    {
        $path = route('profile', $this->username);
        return $append ? "{$path}/{$append}" : $path;
    }
}

resources/views/explore.blade.php
<x-app>
    <div>
        @foreach ($users as $user)
        <a href="{{$user->path()}}" class="flex items-center mb-5 mr-2">

            <img src="{{$user->avatar}}" alt="avatar" style="
            width: 50px;
            height: 50px;" class="rounded-full">


            <h4 class="font-bold px-4"> {{'@'.$user->username}}</h4>
        </a>

        @endforeach
        <div class="pagination">
            {{ $users->links() }}
        </div>
    </div>
</x-app>

resources/views/left-sidebar.blade.php
<ul class="hidden md:block">
    <li><a href="{{route('home')}}" class="font-bold text-lg mb-4 block">Home</a></li>
    <li><a href="{{route('explore')}}" class="font-bold text-lg mb-4 block">Explores</a></li>
    <li><a href="{{ route('profile', auth()->user())}}" class="font-bold text-lg mb-4 block">Profile</a></li>
    <li>
        <form action="/logout" method="post">
            @csrf
            <button class="font-bold text-lg mb-4 block" type="">Log Out</button>
        </form>
    </li>
</ul>

resources/views/new-post-panel.blade.php
<div class="border border-blue-400 rounded-lg py-6 px-8 mb-8">
    <form method="POST" action="/tweets" enctype="multipart/form-data">
        @csrf
        <div class="flex  md:block">
            {{-- input text --}}
            <textarea name="body" class="w-full" placeholder="Tweet Here">
            </textarea>
            {{-- input image --}}
            <div class="image-upload w-6 h-6">
                <label for="file-input">
                    <i class=" material-icons text-gray-500" title="Add Image">photo</i>
                </label>

                <input id="file-input" type="file" name="image" />
            </div>
        </div>

        <hr class="my-4">
        @if (session()->has('message'))
        <div></div>
        <div class="flex items-center bg-blue-400 text-white text-sm font-bold px-2 py-2 m-1 rounded-md" role="alert">
            <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path
                    d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z" />
            </svg>
            <p>{{session()->get('message')}}</p>
        </div>
        @endif
        {{-- menambah error validasi pada textarea --}}
        <div>
            @error('body')
            <p class="text-red-500 text-sm m-2">{{$message}}</p>
            @enderror
        </div>
        <footer class="flex justify-between">
            <img src="{{ auth()->user()->avatar}}" alt="" class="rounded-full mr-2" style="
            width: 50px;
            height: 50px;">
            <button type="submit" class="bg-blue-400 rounded-lg shadow py-2 px-2 text-white "
                style="height: fit-content">TWEET</button>
        </footer>

    </form>

</div>

resources/views/right-sidebar.blade.php
<h3 class="font-bold text-xl mb-4">Friends</h3>
<ul>
    @forelse (auth()->user()->follows as $friend)
    <li>
        <a href="{{route('profile', $friend->username)}}">
            <div class="flex items-center text-sm mb-2">
                <img src="{{$friend->avatar}}" alt="" class="rounded-full mr-2" style="
                width: 40px;
                height: 40px;">
                {{$friend->name}}
            </div>
        </a>
    </li>
    @empty

    <p class=" p-4">No Friends</p>
    @endforelse

</ul>

resources/views/timeline.blade.php
<div class="border-gray-300 rounded-lg shadow bg-gray-200">
    {{-- Tweets --}}
    @forelse ($tweets as $tweet)
    @include('tweet')
    @empty

    <p class="p-4 ">No Tweet.......</p>

    @endforelse

</div>

resources/views/tweet.blade.php
<div class="flex p-4 {{$loop->last ? '': 'border-b border-b-gray-400'}} relative" id="tweet">
    <div class="flex-shrink-0 mr-2">
        {{-- memberi link pd profile dan mengirim parameter wildcard berupa nama dari user tweet --}}
        <a href="{{route('profile', $tweet->user->username)}}">
            <img src="{{$tweet->user->avatar}}" alt="" class="rounded-full mr-2" style="
            width: 50px;
            height: 50px;">
        </a>
    </div>
    <div class="relative">
        <h5 class="font-bold mb-4">
            <a href="{{route('profile', $tweet->user->username)}}">
                {{$tweet->user->name}}
            </a>
        </h5>

        <p class="text-sm mb-4">
            {{$tweet->body}}
        </p>
        <div class="pb-4">
            <img src="{{$tweet->image}}" alt="">
        </div>

        <x-like-button :tweet="$tweet" />

    </div>
    <x-delete-post-button :tweet="$tweet" />

</div>